### ISSUE TITLE
Integration to server

### ISSUE THREAD

**Issue by beatstick** [hubisan/searx-userstyle-dark-theme#2]
This dark theme is exactly what I am looking for. Would it be possible to integrate it server side? I run my own searx-server and it would be much more convenient to have it as default theme on the server and not running a script on every machine/phone at home.

**Comment by hubisan** [comment]
Unfortunately I don't have the time to actually code and test everything and make a pull request on the searx repo. If it's your private server you could play around a bit and try to just place this css file on your server and add an @import rule in the main css file (logicodev.min.css).

**Comment by beatstick** [comment]
Thanks a lot! It works very well. Here's how I did it step by step:
1. copy searx-userstyle-dark-theme.css to /searx/searx/static/themes/oscar/css
2. Edit logicodev.min.css: put 
    @import url("searx-userstyle-dark-theme.css"); 
    at the beginning of the file (no spaces before or after)
3. edit searx-userstyle-dark-theme.css and replace searx.me with the url of your searx-site.

Cheers again, for the great theme.

**Comment by beatstick** [comment]
I only got one problem: The search result box turns white on mouse over: https://imgur.com/a/k1zHT

Is this intended behavior?

**Comment by hubisan** [comment]
This is not intended. Can you inspect the element in your browser? My style should overwrite the default one. This probably has something to do with importing my style before the default one. I just noticed that the color for google at the bottom right of each results also doesn't work.

What you could try:

## Option 1

1. Copy logicodev.min.css to logicodev-2.min.css
2. Replace the content in logicodev.min.css with first an import rule for logicodev-2.min.css and then for searx-userstyle-dark-theme.css to make it load after the default one

## Option 2

- Just copy the css text from searx-userstyle-dark-theme.css to the end of logicodev.min.css

Please let me know if one of those 2 options works.

**Comment by beatstick** [comment]
I tried around with different themes but none worked as I liked. Finally I copy-pasted your theme from another website and now it works as intended: https://imgur.com/a/NyNhM
I might give your other solutions a try as the @import function does not seem to work on chromium or privacy browser (android). 

Edit: I tried option 2 and it still works only with firefox. I have no clue, why. Chromium and privacy browser show the default skin.

**Comment by hubisan** [comment]
Strange that it's not working with Chromium (I assume that you have cleared the cache). If I ever have the time (little kids at home ;-)) I will merge my theme with the official one (remove duplicated styles) so it's possible to just replace the css file with it. Sorry that I can't give you a solution to make it work. Closing this.

**Comment by hubisan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/2eB2N1UR/1-test)
